# Generated by Django 3.2.21 on 2023-09-09 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envio',
            name='destino',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='envio',
            name='origen',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=40),
        ),
    ]
